### ISSUE TITLE
A thank you- word for making this repo

### ISSUE THREAD

**Issue by loneicewolf** [cpeikert/TheoryOfCryptography#11]
### Hello!

While I browsed trough Cryptography-related repos and resources, I came across this one and I just (`really`) **had** to show my appreciation by writing this `issue` (although it's not an issue).

### Thank you for making this Repo!
It has been (and will continue to be ) useful.
Wishes from Sweden! Take care! :)

__Will.__

**Comment by cpeikert** [comment]
Thank you William! I am glad that you find the notes so useful.
